"""add_elevation_to_routes

Revision ID: b02874b51238
Revises: b3673a4d0cc8
Create Date: 2025-11-20 00:43:18.597895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b02874b51238'
down_revision: Union[str, None] = 'b3673a4d0cc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routes', sa.Column('elevation', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('routes', 'elevation')
    # ### end Alembic commands ###

