"""add_location_to_routes

Revision ID: b3673a4d0cc8
Revises: 5f8c6b8b2f3a
Create Date: 2025-11-20 00:26:46.063794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3673a4d0cc8'
down_revision: Union[str, None] = '5f8c6b8b2f3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routes', sa.Column('location', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('routes', 'location')
    # ### end Alembic commands ###

